# because i'm using mac, otherwise just "mysql" will work and will install the latest image (https://hub.docker.com/r/mysql/mysql-server)
FROM mysql/mysql-server:8.0.23

ENV MYSQL_DATABASE="app-database"